const siswa = require("./user");
const admin = require("./admin");
const kelas = require("./kelas");
const todolist = require("./todolist");
const target = require("./target");
const buku = require("./buku");
const konseling = require("./konseling");
const motivasi = require("./motivasi");
const mapel = require("./mapel");
const jadwal = require("./jadwal");
const model = {};

model.siswa = siswa;
model.admin = admin;
model.target = target;
model.todolist = todolist;
model.buku = buku;
model.konseling = konseling;
model.motivasi = motivasi;
model.kelas = kelas;
model.mapel = mapel;
model.jadwal = jadwal;
module.exports = model